spring:
  profiles:
    active:
  build:
    version: ^project.version^
  application:
    name: api-prueba-la-banca
    description: ^project.description^
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/labanca?enabledTLSProtocols=TLSv1.2
    username: root
    password: Lamota80@
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver